# Generated by Django 3.0.3 on 2020-04-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='html',
        ),
    ]
